/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuantForms;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 *
 * @author davidarchilapena
 */
public class B_BoxC extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public B_BoxC() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B004_TP = new javax.swing.JPanel();
        B004_T_4 = new javax.swing.JLabel();
        B004_T_1 = new javax.swing.JLabel();
        B004_T_2 = new javax.swing.JLabel();
        B004_T_3 = new javax.swing.JLabel();
        B004_CP = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        B004_L_1 = new javax.swing.JLabel();
        B004_L_2 = new javax.swing.JLabel();
        B004_L_3 = new javax.swing.JLabel();
        B004_L_4 = new javax.swing.JLabel();
        B004_L_5 = new javax.swing.JLabel();
        B004_L_6 = new javax.swing.JLabel();
        B004_L_7 = new javax.swing.JLabel();
        B004_SL_1 = new javax.swing.JSlider();
        B004_L_8 = new javax.swing.JLabel();
        B004_L_9 = new javax.swing.JLabel();
        B004_SL_2 = new javax.swing.JSlider();
        B004_L_10 = new javax.swing.JLabel();
        B004_L_11 = new javax.swing.JLabel();
        B004_B_1 = new javax.swing.JButton();
        B004_TF_1 = new javax.swing.JTextField();
        B004_TF_5 = new javax.swing.JTextField();
        B004_P_1 = new javax.swing.JPanel();
        B004_L_12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Function Normalizator");

        B004_TP.setBackground(new java.awt.Color(0, 153, 153));

        B004_T_4.setFont(new java.awt.Font("Baskerville", 0, 12)); // NOI18N
        B004_T_4.setForeground(new java.awt.Color(255, 255, 255));
        B004_T_4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B004_T_4.setText("Description");

        B004_T_1.setText("Logo");

        B004_T_2.setFont(new java.awt.Font("Baskerville Old Face", 0, 48)); // NOI18N
        B004_T_2.setForeground(new java.awt.Color(255, 255, 255));
        B004_T_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B004_T_2.setText("QUANT");

        B004_T_3.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B004_T_3.setForeground(new java.awt.Color(255, 255, 255));
        B004_T_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B004_T_3.setText("Particle in a Box: lineal combination animations.");

        javax.swing.GroupLayout B004_TPLayout = new javax.swing.GroupLayout(B004_TP);
        B004_TP.setLayout(B004_TPLayout);
        B004_TPLayout.setHorizontalGroup(
            B004_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B004_TPLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(B004_T_1)
                .addGap(37, 37, 37)
                .addComponent(B004_T_2)
                .addGap(18, 18, 18)
                .addGroup(B004_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B004_T_4, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B004_T_3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        B004_TPLayout.setVerticalGroup(
            B004_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B004_TPLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(B004_T_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(B004_TPLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(B004_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B004_T_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(B004_TPLayout.createSequentialGroup()
                        .addComponent(B004_T_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B004_T_4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        B004_CP.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Baskerville", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("© QUANT 2020");

        javax.swing.GroupLayout B004_CPLayout = new javax.swing.GroupLayout(B004_CP);
        B004_CP.setLayout(B004_CPLayout);
        B004_CPLayout.setHorizontalGroup(
            B004_CPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B004_CPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        B004_CPLayout.setVerticalGroup(
            B004_CPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B004_CPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        B004_L_1.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B004_L_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B004_L_1.setText("Select two different quantum states:");
        B004_L_1.setToolTipText("");

        B004_L_2.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B004_L_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B004_L_2.setText("State 1:");
        B004_L_2.setToolTipText("");

        B004_L_3.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B004_L_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B004_L_3.setText("State 2:");
        B004_L_3.setToolTipText("");

        B004_L_4.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B004_L_4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B004_L_4.setText("Select linear combination coefficients:");
        B004_L_4.setToolTipText("");

        B004_L_5.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B004_L_5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B004_L_5.setText("State 1:");
        B004_L_5.setToolTipText("");

        B004_L_6.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B004_L_6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B004_L_6.setText("State 2:");
        B004_L_6.setToolTipText("");

        B004_L_7.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B004_L_7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B004_L_7.setText("0");
        B004_L_7.setToolTipText("");

        B004_SL_1.setValue(50);

        B004_L_8.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B004_L_8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B004_L_8.setText("1");
        B004_L_8.setToolTipText("");

        B004_L_9.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B004_L_9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B004_L_9.setText("0");
        B004_L_9.setToolTipText("");

        B004_L_10.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B004_L_10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B004_L_10.setText("1");
        B004_L_10.setToolTipText("");

        B004_L_11.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B004_L_11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B004_L_11.setText("Generated Graph:");

        B004_B_1.setText("Combine!");
        B004_B_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B004_B_1ActionPerformed(evt);
            }
        });

        B004_TF_1.setText("n quantum number.");
        B004_TF_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B004_TF_1ActionPerformed(evt);
            }
        });

        B004_TF_5.setText("n quantum number");
        B004_TF_5.setToolTipText("");
        B004_TF_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B004_TF_5ActionPerformed(evt);
            }
        });

        B004_P_1.setBackground(new java.awt.Color(255, 255, 255));

        B004_L_12.setText(" ");

        javax.swing.GroupLayout B004_P_1Layout = new javax.swing.GroupLayout(B004_P_1);
        B004_P_1.setLayout(B004_P_1Layout);
        B004_P_1Layout.setHorizontalGroup(
            B004_P_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B004_P_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(B004_L_12, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        B004_P_1Layout.setVerticalGroup(
            B004_P_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B004_P_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(B004_L_12, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B004_TP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(B004_CP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(B004_L_4, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B004_L_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B004_TF_1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(B004_L_1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B004_L_3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B004_TF_5)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(B004_L_5)
                            .addGap(36, 36, 36)
                            .addComponent(B004_L_7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B004_SL_1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B004_L_8))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(B004_L_6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(B004_L_9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B004_SL_2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B004_L_10)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B004_B_1)
                        .addGap(223, 223, 223)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B004_L_11, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B004_P_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(B004_TP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(B004_P_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(B004_L_1)
                                    .addComponent(B004_L_11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(B004_L_2)
                                    .addComponent(B004_TF_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(B004_L_3)
                                    .addComponent(B004_TF_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B004_L_4)
                                .addGap(18, 18, 18)
                                .addComponent(B004_L_5))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(B004_SL_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B004_L_8, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(B004_L_7))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B004_L_6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B004_SL_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B004_L_10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(B004_L_9)))
                        .addGap(18, 18, 18)
                        .addComponent(B004_B_1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(B004_CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B004_TF_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B004_TF_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B004_TF_1ActionPerformed

    private void B004_TF_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B004_TF_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B004_TF_5ActionPerformed

    private void B004_B_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B004_B_1ActionPerformed
        try {                
         // create a new array of 3 strings, used as input command
            String[] cmdArray = new String[7];
            cmdArray[0] = ""; //Python Path
            cmdArray[1] = ""; //.py path
            
            //+ Inputs
            cmdArray[2] = B004_TF_1.getText(); // Quantum Number 1
            cmdArray[4] = B004_TF_5.getText(); //Quantum Number 2
            int SL1 = B004_SL_1.getValue();
            String SL1s = Integer.toString(SL1);
            cmdArray[5] = SL1s; // Coefficient 1
            int SL2 = B004_SL_1.getValue();
            String SL2s = Integer.toString(SL2);
            cmdArray[6] = SL2s; // Coefficient 2
            
    
                    // print out a message on the console if we want
                       System.out.println("Working");

                    // create a process and execute cmdArray and currect environment
                       Process p = Runtime.getRuntime().exec(cmdArray,null);                

                       String result = null;
                       BufferedReader in =
                           new BufferedReader(new InputStreamReader(p.getInputStream()));
                       String inputLine;
                       while ((inputLine = in.readLine()) != null) {
                           System.out.println(inputLine);
                           if ( result == null )
                               result = "";
                           result += inputLine;
            }
            in.close();
            
            // + Text Outputs
            
            //none       
        }
        catch(IOException e){
        
        }
        
        //Image Outputs
        
        //B003_L_9.setIcon(); // Particle in a Box Graph      
                                            

    }//GEN-LAST:event_B004_B_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_BoxC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B004_B_1;
    private javax.swing.JPanel B004_CP;
    private javax.swing.JLabel B004_L_1;
    private javax.swing.JLabel B004_L_10;
    private javax.swing.JLabel B004_L_11;
    private javax.swing.JLabel B004_L_12;
    private javax.swing.JLabel B004_L_2;
    private javax.swing.JLabel B004_L_3;
    private javax.swing.JLabel B004_L_4;
    private javax.swing.JLabel B004_L_5;
    private javax.swing.JLabel B004_L_6;
    private javax.swing.JLabel B004_L_7;
    private javax.swing.JLabel B004_L_8;
    private javax.swing.JLabel B004_L_9;
    private javax.swing.JPanel B004_P_1;
    private javax.swing.JSlider B004_SL_1;
    private javax.swing.JSlider B004_SL_2;
    private javax.swing.JTextField B004_TF_1;
    private javax.swing.JTextField B004_TF_5;
    private javax.swing.JPanel B004_TP;
    private javax.swing.JLabel B004_T_1;
    private javax.swing.JLabel B004_T_2;
    private javax.swing.JLabel B004_T_3;
    private javax.swing.JLabel B004_T_4;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
