/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuantForms;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 *
 * @author davidarchilapena
 */
public class B_BlackB extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public B_BlackB() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B001_TP = new javax.swing.JPanel();
        B002_T_4 = new javax.swing.JLabel();
        B002_T_1 = new javax.swing.JLabel();
        B002_T_2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        B002_Tabs = new javax.swing.JTabbedPane();
        B002A_P = new javax.swing.JPanel();
        B002A_L_1 = new javax.swing.JLabel();
        B002A_L_2 = new javax.swing.JLabel();
        B002A_SB_1 = new javax.swing.JScrollBar();
        B002A_L_3 = new javax.swing.JLabel();
        B002A_B_1 = new javax.swing.JButton();
        B002B_P = new javax.swing.JPanel();
        B002B_L_1 = new javax.swing.JLabel();
        B002B_L_2 = new javax.swing.JLabel();
        B002B_SB_1 = new javax.swing.JScrollBar();
        B002B_L_3 = new javax.swing.JLabel();
        B002B_B_1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Function Normalizator");

        B001_TP.setBackground(new java.awt.Color(0, 153, 153));

        B002_T_4.setText("Logo");

        B002_T_1.setFont(new java.awt.Font("Baskerville Old Face", 0, 48)); // NOI18N
        B002_T_1.setForeground(new java.awt.Color(255, 255, 255));
        B002_T_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B002_T_1.setText("QUANT");

        B002_T_2.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B002_T_2.setForeground(new java.awt.Color(255, 255, 255));
        B002_T_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B002_T_2.setText("Black Body");

        javax.swing.GroupLayout B001_TPLayout = new javax.swing.GroupLayout(B001_TP);
        B001_TP.setLayout(B001_TPLayout);
        B001_TPLayout.setHorizontalGroup(
            B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B001_TPLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(B002_T_4)
                .addGap(37, 37, 37)
                .addComponent(B002_T_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B002_T_2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        B001_TPLayout.setVerticalGroup(
            B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B001_TPLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(B002_T_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(B001_TPLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(B001_TPLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(B002_T_2))
                    .addComponent(B002_T_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Baskerville", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("© QUANT 2020");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        B002_Tabs.setMaximumSize(new java.awt.Dimension(462, 550));
        B002_Tabs.setMinimumSize(new java.awt.Dimension(462, 550));
        B002_Tabs.setPreferredSize(new java.awt.Dimension(462, 550));

        B002A_L_1.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B002A_L_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B002A_L_1.setText("Select the wavelenght. ");

        B002A_L_2.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B002A_L_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B002A_L_2.setText("100 nm");

        B002A_SB_1.setMaximum(2000);
        B002A_SB_1.setMinimum(100);
        B002A_SB_1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);

        B002A_L_3.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B002A_L_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B002A_L_3.setText("2000 nm");

        B002A_B_1.setText("Show me the curve!");
        B002A_B_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B002A_B_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout B002A_PLayout = new javax.swing.GroupLayout(B002A_P);
        B002A_P.setLayout(B002A_PLayout);
        B002A_PLayout.setHorizontalGroup(
            B002A_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B002A_PLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(B002A_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(B002A_PLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(B002A_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B002A_PLayout.createSequentialGroup()
                                .addComponent(B002A_L_2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163))
                            .addComponent(B002A_SB_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B002A_L_3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(B002A_PLayout.createSequentialGroup()
                        .addComponent(B002A_L_1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(B002A_PLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(B002A_B_1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        B002A_PLayout.setVerticalGroup(
            B002A_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B002A_PLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(B002A_L_1)
                .addGap(18, 18, 18)
                .addGroup(B002A_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B002A_L_2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B002A_SB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B002A_L_3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                .addComponent(B002A_B_1)
                .addGap(14, 14, 14))
        );

        B002_Tabs.addTab("By Wave Lenght", B002A_P);

        B002B_L_1.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B002B_L_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B002B_L_1.setText("Select the tempertature. ");

        B002B_L_2.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B002B_L_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B002B_L_2.setText("0 K");

        B002B_SB_1.setMaximum(2500);
        B002B_SB_1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);

        B002B_L_3.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B002B_L_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B002B_L_3.setText("2500 K");

        B002B_B_1.setText("Show me the curve!");
        B002B_B_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B002B_B_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout B002B_PLayout = new javax.swing.GroupLayout(B002B_P);
        B002B_P.setLayout(B002B_PLayout);
        B002B_PLayout.setHorizontalGroup(
            B002B_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B002B_PLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(B002B_B_1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(B002B_PLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(B002B_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(B002B_PLayout.createSequentialGroup()
                        .addComponent(B002B_L_1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(B002B_PLayout.createSequentialGroup()
                        .addComponent(B002B_L_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B002B_SB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(B002B_L_3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        B002B_PLayout.setVerticalGroup(
            B002B_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B002B_PLayout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(B002B_L_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(B002B_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B002B_L_2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B002B_SB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B002B_L_3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(B002B_B_1)
                .addGap(76, 76, 76))
        );

        B002_Tabs.addTab("By Temperature", B002B_P);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B001_TP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(B002_Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(B001_TP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(B002_Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B002A_B_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B002A_B_1ActionPerformed
     
            String[] pathArray = new String[3];
            
            
            //------- Creation of "python" command -----------------
            pathArray[0] = Path.executable_path; //Executable Path
            pathArray[1] = "B_BlackB_2";
            pathArray[2] = String.valueOf(B002A_SB_1.getValue());          
            //------------------------------------------------------
                        
            PythonProcess pythonProcess = new PythonProcess(pathArray);
            Thread thread = new Thread(pythonProcess);
            thread.start();
                                          
    }//GEN-LAST:event_B002A_B_1ActionPerformed

    private void B002B_B_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B002B_B_1ActionPerformed
      
            String[] pathArray = new String[3];
            
            
            //------- Creation of "python" command -----------------
            pathArray[0] = Path.executable_path; //Executable Path
            pathArray[1] = "B_BlackB_1";
            pathArray[2] = String.valueOf(B002B_SB_1.getValue()); 
            //------------------------------------------------------
                        
            PythonProcess pythonProcess = new PythonProcess(pathArray);
            Thread thread = new Thread(pythonProcess);
            thread.start();   
    }//GEN-LAST:event_B002B_B_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_BlackB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_BlackB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_BlackB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_BlackB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_BlackB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel B001_TP;
    private javax.swing.JButton B002A_B_1;
    private javax.swing.JLabel B002A_L_1;
    private javax.swing.JLabel B002A_L_2;
    private javax.swing.JLabel B002A_L_3;
    private javax.swing.JPanel B002A_P;
    private javax.swing.JScrollBar B002A_SB_1;
    private javax.swing.JButton B002B_B_1;
    private javax.swing.JLabel B002B_L_1;
    private javax.swing.JLabel B002B_L_2;
    private javax.swing.JLabel B002B_L_3;
    private javax.swing.JPanel B002B_P;
    private javax.swing.JScrollBar B002B_SB_1;
    private javax.swing.JLabel B002_T_1;
    private javax.swing.JLabel B002_T_2;
    private javax.swing.JLabel B002_T_4;
    private javax.swing.JTabbedPane B002_Tabs;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
