/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuantForms;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 *
 * @author davidarchilapena
 */
public class B_Box extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public B_Box() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B003_TP = new javax.swing.JPanel();
        B003_T_1 = new javax.swing.JLabel();
        B003_T_2 = new javax.swing.JLabel();
        B003_T_3 = new javax.swing.JLabel();
        B003_T_4 = new javax.swing.JLabel();
        B003_CP = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        B003_L_1 = new javax.swing.JLabel();
        B003_CB_1 = new javax.swing.JComboBox<>();
        B003_L_2 = new javax.swing.JLabel();
        B003_L_5 = new javax.swing.JLabel();
        B003_TF_1 = new javax.swing.JTextField();
        B003_TF_2 = new javax.swing.JTextField();
        B003_L_6 = new javax.swing.JLabel();
        B003_TF_3 = new javax.swing.JTextField();
        B003_TF_4 = new javax.swing.JTextField();
        B003_L_7 = new javax.swing.JLabel();
        B003_TF_5 = new javax.swing.JTextField();
        B003_TF_6 = new javax.swing.JTextField();
        B003_B_1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Function Normalizator");

        B003_TP.setBackground(new java.awt.Color(0, 153, 153));

        B003_T_1.setFont(new java.awt.Font("Baskerville", 0, 12)); // NOI18N
        B003_T_1.setForeground(new java.awt.Color(255, 255, 255));
        B003_T_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B003_T_1.setText("Description");

        B003_T_2.setText("Logo");

        B003_T_3.setFont(new java.awt.Font("Baskerville Old Face", 0, 48)); // NOI18N
        B003_T_3.setForeground(new java.awt.Color(255, 255, 255));
        B003_T_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B003_T_3.setText("QUANT");

        B003_T_4.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B003_T_4.setForeground(new java.awt.Color(255, 255, 255));
        B003_T_4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B003_T_4.setText("Particle in a Box");

        javax.swing.GroupLayout B003_TPLayout = new javax.swing.GroupLayout(B003_TP);
        B003_TP.setLayout(B003_TPLayout);
        B003_TPLayout.setHorizontalGroup(
            B003_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B003_TPLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(B003_T_2)
                .addGap(37, 37, 37)
                .addComponent(B003_T_3)
                .addGap(18, 18, 18)
                .addGroup(B003_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B003_T_1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B003_T_4, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        B003_TPLayout.setVerticalGroup(
            B003_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B003_TPLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(B003_T_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(B003_TPLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(B003_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B003_T_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(B003_TPLayout.createSequentialGroup()
                        .addComponent(B003_T_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B003_T_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        B003_CP.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Baskerville", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("© QUANT 2020");

        javax.swing.GroupLayout B003_CPLayout = new javax.swing.GroupLayout(B003_CP);
        B003_CP.setLayout(B003_CPLayout);
        B003_CPLayout.setHorizontalGroup(
            B003_CPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B003_CPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        B003_CPLayout.setVerticalGroup(
            B003_CPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B003_CPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        B003_L_1.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B003_L_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B003_L_1.setText("Select dimensions");

        B003_CB_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        B003_L_2.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B003_L_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B003_L_2.setText("Select quantum numbers and axis lenght:");

        B003_L_5.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B003_L_5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B003_L_5.setText("In x");

        B003_TF_1.setText("x quantum numer n");
        B003_TF_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B003_TF_1ActionPerformed(evt);
            }
        });

        B003_TF_2.setText("x length");
        B003_TF_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B003_TF_2ActionPerformed(evt);
            }
        });

        B003_L_6.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B003_L_6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B003_L_6.setText("In y");

        B003_TF_3.setText("y quantum numer n");
        B003_TF_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B003_TF_3ActionPerformed(evt);
            }
        });

        B003_TF_4.setText("y length");
        B003_TF_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B003_TF_4ActionPerformed(evt);
            }
        });

        B003_L_7.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B003_L_7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B003_L_7.setText("In z");

        B003_TF_5.setText("z quantum numer n");
        B003_TF_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B003_TF_5ActionPerformed(evt);
            }
        });

        B003_TF_6.setText("z length");
        B003_TF_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B003_TF_6ActionPerformed(evt);
            }
        });

        B003_B_1.setText("Create the Box!");
        B003_B_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B003_B_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B003_TP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(B003_CP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(B003_L_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(B003_L_1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(B003_CB_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(B003_L_6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(B003_TF_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(B003_TF_4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(B003_L_5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(B003_TF_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(B003_TF_2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(B003_L_7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(B003_TF_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(B003_TF_6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(B003_B_1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(B003_TP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B003_L_1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B003_CB_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(B003_L_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B003_TF_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B003_L_5)
                    .addComponent(B003_TF_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B003_TF_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B003_L_6)
                    .addComponent(B003_TF_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B003_TF_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B003_L_7)
                    .addComponent(B003_TF_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(B003_B_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(B003_CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B003_TF_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B003_TF_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B003_TF_1ActionPerformed

    private void B003_TF_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B003_TF_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B003_TF_2ActionPerformed

    private void B003_TF_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B003_TF_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B003_TF_3ActionPerformed

    private void B003_TF_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B003_TF_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B003_TF_4ActionPerformed

    private void B003_TF_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B003_TF_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B003_TF_5ActionPerformed

    private void B003_TF_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B003_TF_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B003_TF_6ActionPerformed

    private void B003_B_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B003_B_1ActionPerformed
      try {                
         // create a new array of 3 strings, used as input command
            String[] cmdArray = new String[3];
            cmdArray[0] = ""; //Python Path
            cmdArray[1] = ""; //.py path
            
            //+ Inputs
            cmdArray[2] = B003_CB_1.getSelectedItem().toString(); // Dimensions
            cmdArray[3] = B003_TF_1.getText(); //x quantum number
            cmdArray[4] = B003_TF_3.getText(); //y quantum number
            cmdArray[5] = B003_TF_5.getText(); //z quantum number
            cmdArray[6] = B003_TF_2.getText(); //x length
            cmdArray[7] = B003_TF_4.getText(); //y length
            cmdArray[8] = B003_TF_6.getText(); //z length
    
                    // print out a message on the console if we want
                       System.out.println("Working");

                    // create a process and execute cmdArray and currect environment
                       Process p = Runtime.getRuntime().exec(cmdArray,null);                

                       String result = null;
                       BufferedReader in =
                           new BufferedReader(new InputStreamReader(p.getInputStream()));
                       String inputLine;
                       while ((inputLine = in.readLine()) != null) {
                           System.out.println(inputLine);
                           if ( result == null )
                               result = "";
                           result += inputLine;
            }
            in.close();
            
            // + Text Outputs
            
            //none       
        }
        catch(IOException e){
        
        }
        
        //Image Outputs
        
        //B003_L_9.setIcon(); // Particle in a Box Graph      
    }//GEN-LAST:event_B003_B_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_Box().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B003_B_1;
    private javax.swing.JComboBox<String> B003_CB_1;
    private javax.swing.JPanel B003_CP;
    private javax.swing.JLabel B003_L_1;
    private javax.swing.JLabel B003_L_2;
    private javax.swing.JLabel B003_L_5;
    private javax.swing.JLabel B003_L_6;
    private javax.swing.JLabel B003_L_7;
    private javax.swing.JTextField B003_TF_1;
    private javax.swing.JTextField B003_TF_2;
    private javax.swing.JTextField B003_TF_3;
    private javax.swing.JTextField B003_TF_4;
    private javax.swing.JTextField B003_TF_5;
    private javax.swing.JTextField B003_TF_6;
    private javax.swing.JPanel B003_TP;
    private javax.swing.JLabel B003_T_1;
    private javax.swing.JLabel B003_T_2;
    private javax.swing.JLabel B003_T_3;
    private javax.swing.JLabel B003_T_4;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
