/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuantForms;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author davidarchilapena
 */
public class B_Huck extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public B_Huck() {
        initComponents();
        setResizable(false);
        
        ImageIcon LogoHuck = new ImageIcon(getClass().getResource("../Images/LogHuck.png"));
        Icon IconHuck = new ImageIcon(LogoHuck.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH));
        B002_T_4.setIcon(IconHuck);
        
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B001_TP = new javax.swing.JPanel();
        B002_T_4 = new javax.swing.JLabel();
        B005_T_1 = new javax.swing.JLabel();
        B005_T_2 = new javax.swing.JLabel();
        B005_T_3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Close = new javax.swing.JButton();
        B005_L_1 = new javax.swing.JLabel();
        B005_L_2 = new javax.swing.JLabel();
        B005_TF_1 = new javax.swing.JTextField();
        B005_B_1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Huckel Simplified Method");

        B001_TP.setBackground(new java.awt.Color(0, 153, 153));

        B005_T_1.setFont(new java.awt.Font("Baskerville Old Face", 0, 48)); // NOI18N
        B005_T_1.setForeground(new java.awt.Color(255, 255, 255));
        B005_T_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B005_T_1.setText("QUANT");

        B005_T_2.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B005_T_2.setForeground(new java.awt.Color(255, 255, 255));
        B005_T_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B005_T_2.setText("Huckel");

        B005_T_3.setFont(new java.awt.Font("Baskerville", 0, 14)); // NOI18N
        B005_T_3.setForeground(new java.awt.Color(255, 255, 255));
        B005_T_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B005_T_3.setText("Simplified Method");

        javax.swing.GroupLayout B001_TPLayout = new javax.swing.GroupLayout(B001_TP);
        B001_TP.setLayout(B001_TPLayout);
        B001_TPLayout.setHorizontalGroup(
            B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B001_TPLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(B002_T_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B005_T_1)
                .addGap(17, 17, 17)
                .addGroup(B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B005_T_2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B005_T_3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        B001_TPLayout.setVerticalGroup(
            B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B001_TPLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B005_T_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B005_T_3))
                        .addComponent(B005_T_2))
                    .addComponent(B002_T_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Baskerville", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("© QUANT 2020");

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Close)))
        );

        B005_L_1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        B005_L_1.setText("Welcome to Huckel Simplified Method calculations.  ");

        B005_L_2.setText("Insert a valid  Simplified Molecular Input Line Entry Specification");

        B005_TF_1.setText("Insert a carbon-made SMILES");
        B005_TF_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B005_TF_1ActionPerformed(evt);
            }
        });

        B005_B_1.setText("Run Huckel");
        B005_B_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B005_B_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B001_TP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B005_B_1)
                    .addComponent(B005_L_1)
                    .addComponent(B005_L_2)
                    .addComponent(B005_TF_1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(B001_TP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B005_L_2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B005_L_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B005_TF_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(B005_B_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B005_TF_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B005_TF_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B005_TF_1ActionPerformed

    private void B005_B_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B005_B_1ActionPerformed
        
            String[] pathArray = new String[3];
            
            
            //------- Creation of "python" command -----------------
            pathArray[0] = Path.executable_path; //Executable Path
            pathArray[1] = "B_Huck";
            pathArray[2] = B005_TF_1.getText();
            //------------------------------------------------------
                        
            PythonProcess pythonProcess = new PythonProcess(pathArray);
            Thread thread = new Thread(pythonProcess);
            thread.start();
    }//GEN-LAST:event_B005_B_1ActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        dispose();
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_Huck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_Huck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_Huck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_Huck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_Huck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel B001_TP;
    private javax.swing.JLabel B002_T_4;
    private javax.swing.JButton B005_B_1;
    private javax.swing.JLabel B005_L_1;
    private javax.swing.JLabel B005_L_2;
    private javax.swing.JTextField B005_TF_1;
    private javax.swing.JLabel B005_T_1;
    private javax.swing.JLabel B005_T_2;
    private javax.swing.JLabel B005_T_3;
    private javax.swing.JButton Close;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
