/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuantForms;


import java.awt.Image;
import java.io.*; 
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author davidarchilapena
 */
public class B_Norm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public B_Norm() {
        initComponents();
        setResizable(false);
        
        ImageIcon LogoNorm = new ImageIcon(getClass().getResource("../Images/LogNorm.png"));
        Icon IconNorm = new ImageIcon(LogoNorm.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH));
        B001_T_4.setIcon(IconNorm);
        
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B001_TP = new javax.swing.JPanel();
        B001_T_4 = new javax.swing.JLabel();
        B001_T_1 = new javax.swing.JLabel();
        B001_T_2 = new javax.swing.JLabel();
        B001_CR = new javax.swing.JPanel();
        B001_CRT = new javax.swing.JLabel();
        Close = new javax.swing.JButton();
        B001_TF_1 = new javax.swing.JTextField();
        B001_L_1 = new javax.swing.JLabel();
        B001_B_1 = new javax.swing.JButton();
        B001_L_2 = new javax.swing.JLabel();
        B001_L_3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Function Normalizator");

        B001_TP.setBackground(new java.awt.Color(0, 153, 153));

        B001_T_1.setFont(new java.awt.Font("Baskerville Old Face", 0, 48)); // NOI18N
        B001_T_1.setForeground(new java.awt.Color(255, 255, 255));
        B001_T_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B001_T_1.setText("QUANT");

        B001_T_2.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B001_T_2.setForeground(new java.awt.Color(255, 255, 255));
        B001_T_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B001_T_2.setText("Function Normalizator");

        javax.swing.GroupLayout B001_TPLayout = new javax.swing.GroupLayout(B001_TP);
        B001_TP.setLayout(B001_TPLayout);
        B001_TPLayout.setHorizontalGroup(
            B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B001_TPLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(B001_T_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(B001_T_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B001_T_2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        B001_TPLayout.setVerticalGroup(
            B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B001_TPLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(B001_T_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(B001_TPLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B001_T_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(B001_TPLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(B001_T_2)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        B001_CR.setBackground(new java.awt.Color(204, 204, 204));

        B001_CRT.setFont(new java.awt.Font("Baskerville", 0, 12)); // NOI18N
        B001_CRT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B001_CRT.setText("© QUANT 2020");

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout B001_CRLayout = new javax.swing.GroupLayout(B001_CR);
        B001_CR.setLayout(B001_CRLayout);
        B001_CRLayout.setHorizontalGroup(
            B001_CRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B001_CRLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(B001_CRT, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Close)
                .addContainerGap())
        );
        B001_CRLayout.setVerticalGroup(
            B001_CRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B001_CRLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(B001_CRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B001_CRT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Close)))
        );

        B001_TF_1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        B001_TF_1.setText("e**-( ((x-1)**2) /2)");
        B001_TF_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        B001_TF_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B001_TF_1ActionPerformed(evt);
            }
        });

        B001_L_1.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B001_L_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B001_L_1.setText("Type the wave function to normalize:");

        B001_B_1.setText("Normalize!");
        B001_B_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B001_B_1ActionPerformed(evt);
            }
        });

        B001_L_2.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B001_L_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B001_L_2.setText("The normalizatin constant is:");

        B001_L_3.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B001_L_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B001_L_3.setText("Enter a function...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B001_TP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(B001_CR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B001_TF_1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B001_L_1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B001_L_2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B001_L_3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(B001_B_1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(B001_TP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(B001_L_1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B001_TF_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(B001_L_2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B001_L_3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(B001_B_1)
                .addGap(107, 107, 107)
                .addComponent(B001_CR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B001_TF_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B001_TF_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B001_TF_1ActionPerformed

    private void B001_B_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B001_B_1ActionPerformed
       
            String[] pathArray = new String[3];
            
            
            //------- Creation of "python" command -----------------
            pathArray[0] = Path.executable_path; //Executable Path
            pathArray[1] = "B_Norm";
            pathArray[2] = B001_TF_1.getText().replaceAll("\\s","");
            //------------------------------------------------------
                 
            PythonProcess pythonProcess = new PythonProcess(pathArray);
            Thread thread = new Thread(pythonProcess);
            thread.start();
            
            
    }//GEN-LAST:event_B001_B_1ActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        dispose();
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_Norm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_Norm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_Norm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_Norm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_Norm().setVisible(true);
            }
        });
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B001_B_1;
    private javax.swing.JPanel B001_CR;
    private javax.swing.JLabel B001_CRT;
    private javax.swing.JLabel B001_L_1;
    private javax.swing.JLabel B001_L_2;
    private javax.swing.JLabel B001_L_3;
    private javax.swing.JTextField B001_TF_1;
    private javax.swing.JPanel B001_TP;
    private javax.swing.JLabel B001_T_1;
    private javax.swing.JLabel B001_T_2;
    private javax.swing.JLabel B001_T_4;
    private javax.swing.JButton Close;
    // End of variables declaration//GEN-END:variables
}
