/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuantForms;


import java.io.*; 

/**
 *
 * @author davidarchilapena
 */
public class B_Norm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public B_Norm() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B001_TP = new javax.swing.JPanel();
        B001_T_3 = new javax.swing.JLabel();
        B001_T_4 = new javax.swing.JLabel();
        B001_T_1 = new javax.swing.JLabel();
        B001_T_2 = new javax.swing.JLabel();
        B001_CR = new javax.swing.JPanel();
        B001_CRT = new javax.swing.JLabel();
        B001_TF_1 = new javax.swing.JTextField();
        B001_L_1 = new javax.swing.JLabel();
        B001_B_1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Function Normalizator");

        B001_TP.setBackground(new java.awt.Color(0, 153, 153));

        B001_T_3.setFont(new java.awt.Font("Baskerville", 0, 12)); // NOI18N
        B001_T_3.setForeground(new java.awt.Color(255, 255, 255));
        B001_T_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B001_T_3.setText("Description");

        B001_T_4.setText("Logo");

        B001_T_1.setFont(new java.awt.Font("Baskerville Old Face", 0, 48)); // NOI18N
        B001_T_1.setForeground(new java.awt.Color(255, 255, 255));
        B001_T_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B001_T_1.setText("QUANT");

        B001_T_2.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B001_T_2.setForeground(new java.awt.Color(255, 255, 255));
        B001_T_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B001_T_2.setText("Function Normalizator");

        javax.swing.GroupLayout B001_TPLayout = new javax.swing.GroupLayout(B001_TP);
        B001_TP.setLayout(B001_TPLayout);
        B001_TPLayout.setHorizontalGroup(
            B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B001_TPLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(B001_T_4)
                .addGap(37, 37, 37)
                .addComponent(B001_T_1)
                .addGap(18, 18, 18)
                .addGroup(B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B001_T_3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B001_T_2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        B001_TPLayout.setVerticalGroup(
            B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B001_TPLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(B001_T_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(B001_TPLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(B001_TPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B001_T_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(B001_TPLayout.createSequentialGroup()
                        .addComponent(B001_T_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B001_T_3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        B001_CR.setBackground(new java.awt.Color(204, 204, 204));

        B001_CRT.setFont(new java.awt.Font("Baskerville", 0, 12)); // NOI18N
        B001_CRT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B001_CRT.setText("© QUANT 2020");

        javax.swing.GroupLayout B001_CRLayout = new javax.swing.GroupLayout(B001_CR);
        B001_CR.setLayout(B001_CRLayout);
        B001_CRLayout.setHorizontalGroup(
            B001_CRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B001_CRLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(B001_CRT, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        B001_CRLayout.setVerticalGroup(
            B001_CRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B001_CRLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(B001_CRT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        B001_TF_1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        B001_TF_1.setText("﻿e**-( ((x-1)**2) /2)");
        B001_TF_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        B001_TF_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B001_TF_1ActionPerformed(evt);
            }
        });

        B001_L_1.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B001_L_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B001_L_1.setText("Type the wave function to normalize:");

        B001_B_1.setText("Normalize!");
        B001_B_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B001_B_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B001_TP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(B001_CR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B001_TF_1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B001_L_1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(320, 320, 320))
            .addGroup(layout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(B001_B_1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(B001_TP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(B001_L_1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(B001_TF_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(B001_B_1)
                .addGap(135, 135, 135)
                .addComponent(B001_CR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B001_TF_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B001_TF_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B001_TF_1ActionPerformed

    private void B001_B_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B001_B_1ActionPerformed
        try {                
         // create a new array of 3 strings, used as input command
            String[] cmdArray = new String[3];
            cmdArray[0] = "python3"; //Python Path
            cmdArray[1] = "/Users/davidarchilapena/NetBeansProjects/Quant/src/Python/B_norm.py";//.py path
            
            //+ Inputs
            cmdArray[2] = B001_TF_1.getText(); // Function to normalice
    
                    // print out a message on the console if we want
                       System.out.println("Working");

                    // create a process and execute cmdArray and currect environment
                       Process p = Runtime.getRuntime().exec(cmdArray,null);                

                       String result = null;
                       BufferedReader in =
                           new BufferedReader(new InputStreamReader(p.getInputStream()));
                       String inputLine;
                       while ((inputLine = in.readLine()) != null) {
                           System.out.println(inputLine);
                           if ( result == null )
                               result = "";
                           result += inputLine;
            }
            in.close();
            
            // + Text Outputs
            
            //B001_L_5.setText(result); // Normalization Constant              
        }
        catch(IOException e){
        
        }
        
        //Image Outputs
        
        //B001_P_3.setIcon(); // Function Graph
    }//GEN-LAST:event_B001_B_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_Norm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_Norm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_Norm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_Norm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_Norm().setVisible(true);
            }
        });
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B001_B_1;
    private javax.swing.JPanel B001_CR;
    private javax.swing.JLabel B001_CRT;
    private javax.swing.JLabel B001_L_1;
    private javax.swing.JTextField B001_TF_1;
    private javax.swing.JPanel B001_TP;
    private javax.swing.JLabel B001_T_1;
    private javax.swing.JLabel B001_T_2;
    private javax.swing.JLabel B001_T_3;
    private javax.swing.JLabel B001_T_4;
    // End of variables declaration//GEN-END:variables
}
