/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuantForms;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author davidarchilapena
 */
public class C_Bohr extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public C_Bohr() {
        initComponents();
        setResizable(false);
        
        ImageIcon LogoOrbs = new ImageIcon(getClass().getResource("../Images/LogOrbs.png"));
        Icon IconOrbs = new ImageIcon(LogoOrbs.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH));
        C003_T_1.setIcon(IconOrbs);
        
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        C003_T_3 = new javax.swing.JPanel();
        C003_T_1 = new javax.swing.JLabel();
        B006_T_2 = new javax.swing.JLabel();
        B006_T_1 = new javax.swing.JLabel();
        B006_T_3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Close = new javax.swing.JButton();
        B006_L_1 = new javax.swing.JLabel();
        B006_B_1 = new javax.swing.JButton();
        B006_L_2 = new javax.swing.JLabel();
        B006_L_3 = new javax.swing.JLabel();
        B006_TF_1 = new javax.swing.JTextField();
        B006_TF_2 = new javax.swing.JTextField();
        B006_L_4 = new javax.swing.JLabel();
        B006_TF_3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bohr SommerFeld Orbits");

        C003_T_3.setBackground(new java.awt.Color(0, 153, 153));

        B006_T_2.setFont(new java.awt.Font("Baskerville Old Face", 0, 48)); // NOI18N
        B006_T_2.setForeground(new java.awt.Color(255, 255, 255));
        B006_T_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B006_T_2.setText("QUANT");

        B006_T_1.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B006_T_1.setForeground(new java.awt.Color(255, 255, 255));
        B006_T_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B006_T_1.setText(" Bohr SommerFeld");

        B006_T_3.setFont(new java.awt.Font("Baskerville", 0, 14)); // NOI18N
        B006_T_3.setForeground(new java.awt.Color(255, 255, 255));
        B006_T_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B006_T_3.setText("Orbits");

        javax.swing.GroupLayout C003_T_3Layout = new javax.swing.GroupLayout(C003_T_3);
        C003_T_3.setLayout(C003_T_3Layout);
        C003_T_3Layout.setHorizontalGroup(
            C003_T_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(C003_T_3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(C003_T_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B006_T_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(C003_T_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B006_T_1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(C003_T_3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(B006_T_3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        C003_T_3Layout.setVerticalGroup(
            C003_T_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(C003_T_3Layout.createSequentialGroup()
                .addGroup(C003_T_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(C003_T_3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(C003_T_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(C003_T_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(B006_T_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B006_T_3))
                            .addComponent(B006_T_1)))
                    .addGroup(C003_T_3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(C003_T_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Baskerville", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("© QUANT 2020");

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Close)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Close)))
        );

        B006_L_1.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B006_L_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B006_L_1.setText("Select the following parameters:");
        B006_L_1.setToolTipText("");

        B006_B_1.setText("Create the  Bohr SommerFeld Orbit!");
        B006_B_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B006_B_1ActionPerformed(evt);
            }
        });

        B006_L_2.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B006_L_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B006_L_2.setText("n value:");
        B006_L_2.setToolTipText("");

        B006_L_3.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B006_L_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B006_L_3.setText("k value:");
        B006_L_3.setToolTipText("");

        B006_TF_1.setText("Quantum number");
        B006_TF_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B006_TF_1ActionPerformed(evt);
            }
        });

        B006_TF_2.setText("Quantum number");
        B006_TF_2.setToolTipText("");
        B006_TF_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B006_TF_2ActionPerformed(evt);
            }
        });

        B006_L_4.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        B006_L_4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B006_L_4.setText("Z value:");
        B006_L_4.setToolTipText("");

        B006_TF_3.setText("Nuclear number");
        B006_TF_3.setToolTipText("");
        B006_TF_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B006_TF_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(C003_T_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B006_B_1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B006_L_4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B006_TF_3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B006_L_2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B006_TF_1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(B006_L_1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B006_L_3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B006_TF_2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(C003_T_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(B006_L_1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B006_L_2)
                    .addComponent(B006_TF_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B006_L_3)
                    .addComponent(B006_TF_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B006_L_4)
                    .addComponent(B006_TF_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(B006_B_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B006_TF_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B006_TF_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B006_TF_1ActionPerformed

    private void B006_TF_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B006_TF_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B006_TF_2ActionPerformed

    private void B006_TF_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B006_TF_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B006_TF_3ActionPerformed

    private void B006_B_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B006_B_1ActionPerformed
       
            String[] pathArray = new String[5];
            
            
            //------- Creation of "python" command -----------------
            pathArray[0] = Path.executable_path; //Executable Path
            pathArray[1] = "C_Bohr";
            pathArray[2] = B006_TF_1.getText();
            pathArray[3] = B006_TF_2.getText();
            pathArray[4] = B006_TF_3.getText();
            //------------------------------------------------------
                        
            
            PythonProcess pythonProcess = new PythonProcess(pathArray);
            Thread thread = new Thread(pythonProcess);
            thread.start();
    }//GEN-LAST:event_B006_B_1ActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_Bohr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_Bohr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_Bohr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_Bohr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_Bohr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B006_B_1;
    private javax.swing.JLabel B006_L_1;
    private javax.swing.JLabel B006_L_2;
    private javax.swing.JLabel B006_L_3;
    private javax.swing.JLabel B006_L_4;
    private javax.swing.JTextField B006_TF_1;
    private javax.swing.JTextField B006_TF_2;
    private javax.swing.JTextField B006_TF_3;
    private javax.swing.JLabel B006_T_1;
    private javax.swing.JLabel B006_T_2;
    private javax.swing.JLabel B006_T_3;
    private javax.swing.JLabel C003_T_1;
    private javax.swing.JPanel C003_T_3;
    private javax.swing.JButton Close;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
