/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuantForms;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author davidarchilapena
 */
public class D_CBS extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public D_CBS() {
        initComponents();
        setResizable(false);
        
        ImageIcon LogoCBS = new ImageIcon(getClass().getResource("../Images/LogCBS.png"));
        Icon IconCBS = new ImageIcon(LogoCBS.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH));
        C004_T_1.setIcon(IconCBS);
        
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Close = new javax.swing.JButton();
        Close1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        C004_T_1 = new javax.swing.JLabel();
        C004_T_2 = new javax.swing.JLabel();
        C004_T_3 = new javax.swing.JLabel();
        C004_T_4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Close2 = new javax.swing.JButton();
        D003_L_1 = new javax.swing.JLabel();
        D003_B_1 = new javax.swing.JButton();
        D003_L_3 = new javax.swing.JLabel();
        D003_L_2 = new javax.swing.JLabel();
        D003_TF_1 = new javax.swing.JTextField();
        D003_L_4 = new javax.swing.JLabel();
        D003_L_5 = new javax.swing.JLabel();
        D003_TF_2 = new javax.swing.JTextField();
        D003_TF_3 = new javax.swing.JTextField();
        D003_TF_4 = new javax.swing.JTextField();
        D003_L_6 = new javax.swing.JLabel();
        D003_TF_5 = new javax.swing.JTextField();

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        Close1.setText("Close");
        Close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Function Normalizator");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        C004_T_2.setFont(new java.awt.Font("Baskerville Old Face", 0, 48)); // NOI18N
        C004_T_2.setForeground(new java.awt.Color(255, 255, 255));
        C004_T_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C004_T_2.setText("QUANT");

        C004_T_3.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        C004_T_3.setForeground(new java.awt.Color(255, 255, 255));
        C004_T_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        C004_T_3.setText("CBS");

        C004_T_4.setFont(new java.awt.Font("Baskerville", 0, 14)); // NOI18N
        C004_T_4.setForeground(new java.awt.Color(255, 255, 255));
        C004_T_4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        C004_T_4.setText("Extrapolation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(C004_T_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(C004_T_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C004_T_3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C004_T_4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(C004_T_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C004_T_3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(C004_T_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(C004_T_4)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Baskerville", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("© QUANT 2020");

        Close2.setText("Close");
        Close2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Close2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Close2)))
        );

        D003_L_1.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        D003_L_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D003_L_1.setText("Enter the energy obtained with each Basis Set:");
        D003_L_1.setToolTipText("");

        D003_B_1.setText("Extrapolate!");
        D003_B_1.setActionCommand("");
        D003_B_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D003_B_1ActionPerformed(evt);
            }
        });

        D003_L_3.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        D003_L_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D003_L_3.setText("cc-pVTZ:");
        D003_L_3.setToolTipText("");

        D003_L_2.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        D003_L_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D003_L_2.setText("cc-pVDZ:");
        D003_L_2.setToolTipText("");

        D003_TF_1.setText("-128.488775551593");
        D003_TF_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D003_TF_1ActionPerformed(evt);
            }
        });

        D003_L_4.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        D003_L_4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D003_L_4.setText("cc-pVQZ:");
        D003_L_4.setToolTipText("");

        D003_L_5.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        D003_L_5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D003_L_5.setText("cc-PV5Z:");
        D003_L_5.setToolTipText("");

        D003_TF_2.setText("-128.531861636113");
        D003_TF_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D003_TF_2ActionPerformed(evt);
            }
        });

        D003_TF_3.setText("-128.543469659171");
        D003_TF_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D003_TF_3ActionPerformed(evt);
            }
        });

        D003_TF_4.setText("-128.546770130004");
        D003_TF_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D003_TF_4ActionPerformed(evt);
            }
        });

        D003_L_6.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        D003_L_6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D003_L_6.setText("cc-PV6Z:");
        D003_L_6.setToolTipText("");

        D003_TF_5.setText("-128.547061101241");
        D003_TF_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D003_TF_5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(D003_L_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D003_L_3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D003_L_4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D003_L_5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D003_L_6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(D003_TF_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D003_TF_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D003_TF_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D003_TF_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D003_TF_5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(D003_L_1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(D003_B_1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(D003_L_1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D003_L_2)
                    .addComponent(D003_TF_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D003_L_3)
                    .addComponent(D003_TF_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D003_L_4)
                    .addComponent(D003_TF_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D003_L_5)
                    .addComponent(D003_TF_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D003_L_6)
                    .addComponent(D003_TF_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(D003_B_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        D003_B_1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void D003_TF_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D003_TF_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D003_TF_1ActionPerformed

    private void D003_TF_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D003_TF_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D003_TF_2ActionPerformed

    private void D003_TF_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D003_TF_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D003_TF_3ActionPerformed

    private void D003_TF_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D003_TF_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D003_TF_4ActionPerformed

    private void D003_B_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D003_B_1ActionPerformed
                  
            String[] pathArray = new String[6];
            
            
            //------- Creation of "python" command -----------------
            pathArray[0] = Path.executable_path; //Executable Path
            pathArray[1] = "C_CBS";
            pathArray[2] = D003_TF_1.getText();
            pathArray[3] = D003_TF_2.getText();
            pathArray[4] = D003_TF_3.getText();
            pathArray[5] = D003_TF_4.getText();
            pathArray[6] = D003_TF_5.getText();
            //------------------------------------------------------
                        
            PythonProcess pythonProcess = new PythonProcess(pathArray);
            Thread thread = new Thread(pythonProcess);
            thread.start();
    }//GEN-LAST:event_D003_B_1ActionPerformed

    private void D003_TF_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D003_TF_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D003_TF_5ActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        dispose();
    }//GEN-LAST:event_CloseActionPerformed

    private void Close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Close1ActionPerformed

    private void Close2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Close2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_CBS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_CBS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_CBS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_CBS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new D_CBS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel C004_T_1;
    private javax.swing.JLabel C004_T_2;
    private javax.swing.JLabel C004_T_3;
    private javax.swing.JLabel C004_T_4;
    private javax.swing.JButton Close;
    private javax.swing.JButton Close1;
    private javax.swing.JButton Close2;
    private javax.swing.JButton D003_B_1;
    private javax.swing.JLabel D003_L_1;
    private javax.swing.JLabel D003_L_2;
    private javax.swing.JLabel D003_L_3;
    private javax.swing.JLabel D003_L_4;
    private javax.swing.JLabel D003_L_5;
    private javax.swing.JLabel D003_L_6;
    private javax.swing.JTextField D003_TF_1;
    private javax.swing.JTextField D003_TF_2;
    private javax.swing.JTextField D003_TF_3;
    private javax.swing.JTextField D003_TF_4;
    private javax.swing.JTextField D003_TF_5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
